# Generated by Django 5.1.7 on 2025-04-27 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimType', models.IntegerField()),
                ('StayDuration', models.FloatField()),
                ('cost', models.FloatField()),
                ('num_diagnoses', models.IntegerField()),
                ('DiagnosisCategory', models.IntegerField()),
                ('num_procedures', models.IntegerField()),
                ('first_procedure', models.IntegerField()),
                ('Gender', models.IntegerField()),
                ('Race', models.IntegerField()),
                ('isWeekend', models.IntegerField()),
                ('ClaimDuration', models.FloatField()),
                ('ClaimDayOfYear', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('first_diagnosis', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
