# Generated by Django 5.1.7 on 2025-04-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalclaim',
            name='ClaimDayOfYear',
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='ClaimDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
