# Generated by Django 5.1.7 on 2025-05-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_remove_medicalclaim_claimdayofyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalclaim',
            name='first_diagnosis',
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='ClaimDay_Cos',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='ClaimdDy_Sin',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalclaim',
            name='isWeekend',
            field=models.BooleanField(default=False),
        ),
    ]
